### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by midspace** [midspace/Space-Engineers-Admin-script-mod#71]
As noted by SiliconPot in the Steam workshop comments.

Exception occured: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
```
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at midspace.adminscripts.ConnectionHelper.ProcessServerData(String dataString)
at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayerSyncObject.ModMessageRecieved(CustomModMsg& msg, MyNetworkClient sender)
at Sandbox.Game.Multiplayer.MySyncLayer.MyCallbackBase`1.Handle(TMsg& msg, UInt64 sender, TimeSpan timestamp)
```

**Comment by midspace** [comment]
Log files
http://forum.keenswh.com/threads/the-game-crashes-when-try-to-access-the-server.7365559/#post-1286811148

**Comment by midspace** [comment]
Additional from DJ Arghlex.
Believes it might be a read/write problem in the server's folder.

"Permission: Loading permission... Please try again later."
http://arghlex.net/u/6JKMokw4lG.png

**Comment by Spcemarine** [comment]
It appears that these errors are unrelated. For the first two I have, at least, attempts to fix them but since I'm not able to reproduce them it is a little difficult to figure out what is wrong.
For the last one with the permissions I don't really have an idea why it occurs. Generally it means that the client wasn't able to receive it's level from the server. The level is sent with the response to the connection request so in conclusion the request wasn't processed and I can't really imagine that because there would have been an exception if that was the case. Basically that's why I don't have a clue what is wrong with this, but at least it does not crash the server or the client. However, I'm going to make the client request it's permissions if it didn't receive it after a certain time is up.

**Comment by midspace** [comment]
You just beat me to my check in. I'm going through the changes now. :(

**Comment by midspace** [comment]
1. I've added additional logging for the ProcessServerData and split the exception handling, in case there is an Action crash, and not a deserialize fault.

2. I reproduced the "Permission: Loading permission... " momentarily when the I fouled up the deserialize in ProcessServerData. The two seem related, and may be due more to bad or old data.

3. I'm not sure what went wrong here, but I'm I think it may be more due to the server still running an older version of the Mod and the server hasn't updated yet, causing the Client with the newer mod to crash inappropriate data.
Exception occured: System.InvalidOperationException: There was an error reflecting type 'midspace.adminscripts.Messages.MessageContainer'. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.


I'm wondering if we should add a Version to the MessageBase or the content, and we update when I upload a new release, that way if a Client connects with a new version, the Server and Admin can be informed, or at least ignore the message.

**Comment by midspace** [comment]
That matches with the error that Vitold is getting.
Ah, going to have to remote into home to download and fix. (at work currently.)


2015-08-03 21:30:59.433 - Thread:   1 ->  Exception occured: System.InvalidOperationException: There was an error reflecting field 'Content'. ---> System.InvalidOperationException: There was an error reflecting type 'midspace.adminscripts.Messages.MessageBase'. ---> System.InvalidOperationException: There was an error reflecting type 'midspace.adminscripts.Messages.MessageAdminNotification'. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

**Comment by midspace** [comment]
Have updated on Steam.

**Comment by zrisher** [comment]
Similar issue reported by some people joining my server:

* Server restarted at 1 am EST
* Mod updated at 4 am EST
* Most clients join without issue
* Some clients get errors downloading mods or this error: `System.InvalidOperationException: There was an error reflecting field 'Content'.` http://pastebin.com/bVzPfM4G
* Server restarts and redownloads mod at 7:30 pm EST
* Same client gets error `System.InvalidOperationException: There was an error reflecting type 'midspace.adminscripts.Messages.MessageContainer'` http://pastebin.com/c6QhXqpQ
* Client deletes mods and redownloads
* Client gets same error http://pastebin.com/wmzQBVZf

**Comment by zrisher** [comment]
For most clients it doesnt matter if they mod isn't working properly for them, it's far more important they be able to join the game than have this functionality. Could you wrap the logic that's raising these issues in a try-catch?

**Comment by midspace** [comment]
zrisher we've literally just updated it 17 minutes ago, so please restart the server and try it again.
We have added additional logging and exception handling to address these issues.

**Comment by zrisher** [comment]
Yep I saw that, we just restarted to try to fix so I'm going to give it a bit, will do later tonight. Either way, this does seem like another area that needs a try-catch.

**Comment by midspace** [comment]
Are either of you able to test MOTD and see if that still works as expected? If there is any failure in the messaging then use of the MOTD should show it.

**Comment by zrisher** [comment]
I can confirm that people who were able to join the server without issues could see the MOTD as well. But no idea for those who had problems, the game crashed before they were able to join. 

I just restarted, the people having issues will give it a go again tomorrow.

**Comment by midspace** [comment]
I believe we've fixed all the crash issues now.
I've left this issue open to improve the code I checked in.

**Comment by zrisher** [comment]
The same client above is still getting a crash when loading into the game (after hitting spawn screen, before final loading is complete):
http://pastebin.com/5JkGAV1e

Both he and the server are running release.

Looks like serialization issues on client init in AdminNotification (not an admin so not sure why he'd be getting one of those). 

It looks like ChatCommandLogic.UpdateBeforeSimulation() does not use a try-catch. If it's too expensive to implement there, could we at least have it in the Init, Update10, and Update100 methods it calls? It would be unfortunate if his commands didn't work, but it's a much bigger issue that he can't join the game at all without it crashing.

**Comment by midspace** [comment]
It looks like AdminNotification is throwing exception on serilize. Will need to have a look at the ProtoBuf attributes on it.

**Comment by midspace** [comment]
Have updated the Admin mod. Please tell me we've nailed the issues.

**Comment by zrisher** [comment]
Thank you, waiting for a good time for a restart probably a few hours, will let you know.

**Comment by midspace** [comment]
Something has gone wrong, so I've rolled back the update.
I've pushed the latest code to my Beta mod for further testing before releasing again.
http://steamcommunity.com/sharedfiles/filedetails/?id=387257948


I've had one user give me the following, which seems strange as the the Timer I've clearly patched:
````
2015-08-06 02:03:46.465 - Thread:   1 ->  Player entered: Digi (76561197985528887)
2015-08-06 02:03:50.743 - Thread:   1 ->  World request received: Digi
2015-08-06 02:03:50.745 - Thread:   1 ->  ...responding
2015-08-06 02:04:04.531 - Thread:   1 ->  Exception occured: System.ArgumentException: Invalid value '0' for parameter 'interval'.
   at System.Timers.Timer..ctor(Double interval)
   at midspace.adminscripts.ServerConfig..ctor(List`1 commands)
   at midspace.adminscripts.ChatCommandLogic.InitServer()
   at midspace.adminscripts.ChatCommandLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
```

**Comment by midspace** [comment]
I want to cry. It looks like I had partially merged code in my main branch when I brought in SpaceMarines changes and then published to Steam.
Space Engineers would have no doubt said the mod was broken and not loaded anything.
Hence the comment "no errors, just not working"

**Comment by zrisher** [comment]
Ah that sucks, did you have your changes backed up on another branch by chance?

Can confirm same error right now. Even without fixing this, if you could just wrap ChatCommandLogic.Init in a try-catch I could stop bothering you for an extended period of time : )

**Comment by midspace** [comment]
Which code? Git, Workshop 316190120, or 387257948 ?

I rolledback the public mod 316190120 (and re-fixed the Timer()), so that should be right.
I've updated Git, but haven't tested it as yet. I can't at work.

**Comment by zrisher** [comment]
316190120

**Comment by midspace** [comment]
387257948 midspace Beta has been updated for testing.
I'd like to make sure this one isn't broken before I release to the public mod this time.

**Comment by zrisher** [comment]
It looks like your prod release 316190120 is more up to date, I'd prefer to test using that and your Timer fix (might be related), does that include your fix for the above? I don't see a separate branch relating to your dev code.

**Comment by midspace** [comment]
It was released almost 5 hours ago.
There are no comments on Steam so far.

**Comment by zrisher** [comment]
Updated 316190120, that player will attempt connecting tomorrow.

**Comment by zrisher** [comment]
FIXED! Thank you!!!!

**Comment by midspace** [comment]
No further comments or complaints have been received about this, so I'm closing this issue.
